//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleIdServer.Saml.Sp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleIdServer.Saml.Sp.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature of the Assertion is not valid.
        /// </summary>
        internal static string BadAssertionSignature {
            get {
                return ResourceManager.GetString("BadAssertionSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IDP metadata doesn&apos;t have IDP Descriptor.
        /// </summary>
        internal static string BadIdpMetadata {
            get {
                return ResourceManager.GetString("BadIdpMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IDP doesn&apos;t have a valid SingleSignOn location.
        /// </summary>
        internal static string BadIDPSingleSignOnLocation {
            get {
                return ResourceManager.GetString("BadIDPSingleSignOnLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not recognized as an Identity Provider (IDP).
        /// </summary>
        internal static string BadRelyingPartyIdpMetadata {
            get {
                return ResourceManager.GetString("BadRelyingPartyIdpMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAML Response cannot be decompressed.
        /// </summary>
        internal static string BadSamlResponseCompression {
            get {
                return ResourceManager.GetString("BadSamlResponseCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature of the Response is not valid.
        /// </summary>
        internal static string BadSamlResponseSignature {
            get {
                return ResourceManager.GetString("BadSamlResponseSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAML Response is not correct.
        /// </summary>
        internal static string BadSamlResponseXml {
            get {
                return ResourceManager.GetString("BadSamlResponseXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature passed in the query is invalid.
        /// </summary>
        internal static string BadSignature {
            get {
                return ResourceManager.GetString("BadSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not Assertion in the SAML Response.
        /// </summary>
        internal static string MissingAssertion {
            get {
                return ResourceManager.GetString("MissingAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no certificate in the descriptor.
        /// </summary>
        internal static string MissingCertificateInDescriptor {
            get {
                return ResourceManager.GetString("MissingCertificateInDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} is missing.
        /// </summary>
        internal static string MissingParameter {
            get {
                return ResourceManager.GetString("MissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no certificate which can be used to check the signature.
        /// </summary>
        internal static string MissingSignatureCertificates {
            get {
                return ResourceManager.GetString("MissingSignatureCertificates", resourceCulture);
            }
        }
    }
}
